/* tslint:disable */
/* eslint-disable */
/**
 * CertificatesManagerApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificateTypeDTO
 */
export interface CertificateTypeDTO {
    /**
     * 
     * @type {string}
     * @memberof CertificateTypeDTO
     */
    handle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CertificateTypeDTO
     */
    name?: string | null;
}

/**
 * Check if a given object implements the CertificateTypeDTO interface.
 */
export function instanceOfCertificateTypeDTO(value: object): value is CertificateTypeDTO {
    return true;
}

export function CertificateTypeDTOFromJSON(json: any): CertificateTypeDTO {
    return CertificateTypeDTOFromJSONTyped(json, false);
}

export function CertificateTypeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificateTypeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'handle': json['handle'] == null ? undefined : json['handle'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CertificateTypeDTOToJSON(value?: CertificateTypeDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'handle': value['handle'],
        'name': value['name'],
    };
}

