/* tslint:disable */
/* eslint-disable */
/**
 * CertificatesManagerApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentDTO
 */
export interface CommentDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    comment?: string | null;
}

/**
 * Check if a given object implements the CommentDTO interface.
 */
export function instanceOfCommentDTO(value: object): value is CommentDTO {
    return true;
}

export function CommentDTOFromJSON(json: any): CommentDTO {
    return CommentDTOFromJSONTyped(json, false);
}

export function CommentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'] == null ? undefined : json['userName'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function CommentDTOToJSON(value?: CommentDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userName': value['userName'],
        'comment': value['comment'],
    };
}

