/* tslint:disable */
/* eslint-disable */
/**
 * CertificatesManagerApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentDTO
 */
export interface CreateCommentDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDTO
     */
    userHandle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDTO
     */
    commentText?: string | null;
}

/**
 * Check if a given object implements the CreateCommentDTO interface.
 */
export function instanceOfCreateCommentDTO(value: object): value is CreateCommentDTO {
    return true;
}

export function CreateCommentDTOFromJSON(json: any): CreateCommentDTO {
    return CreateCommentDTOFromJSONTyped(json, false);
}

export function CreateCommentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'userHandle': json['userHandle'] == null ? undefined : json['userHandle'],
        'commentText': json['commentText'] == null ? undefined : json['commentText'],
    };
}

export function CreateCommentDTOToJSON(value?: CreateCommentDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userHandle': value['userHandle'],
        'commentText': value['commentText'],
    };
}

