/* tslint:disable */
/* eslint-disable */
/**
 * CertificatesManagerApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface UpdateCertificateDTO
 */
export interface UpdateCertificateDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateCertificateDTO
     */
    supplierHandle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCertificateDTO
     */
    certificateTypeHandle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCertificateDTO
     */
    validFrom?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCertificateDTO
     */
    validTo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCertificateDTO
     */
    document?: string | null;
    /**
     * 
     * @type {Array<UserDTO>}
     * @memberof UpdateCertificateDTO
     */
    participants?: Array<UserDTO> | null;
}

/**
 * Check if a given object implements the UpdateCertificateDTO interface.
 */
export function instanceOfUpdateCertificateDTO(value: object): value is UpdateCertificateDTO {
    return true;
}

export function UpdateCertificateDTOFromJSON(json: any): UpdateCertificateDTO {
    return UpdateCertificateDTOFromJSONTyped(json, false);
}

export function UpdateCertificateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCertificateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'supplierHandle': json['supplierHandle'] == null ? undefined : json['supplierHandle'],
        'certificateTypeHandle': json['certificateTypeHandle'] == null ? undefined : json['certificateTypeHandle'],
        'validFrom': json['validFrom'] == null ? undefined : json['validFrom'],
        'validTo': json['validTo'] == null ? undefined : json['validTo'],
        'document': json['document'] == null ? undefined : json['document'],
        'participants': json['participants'] == null ? undefined : ((json['participants'] as Array<any>).map(UserDTOFromJSON)),
    };
}

export function UpdateCertificateDTOToJSON(value?: UpdateCertificateDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'supplierHandle': value['supplierHandle'],
        'certificateTypeHandle': value['certificateTypeHandle'],
        'validFrom': value['validFrom'],
        'validTo': value['validTo'],
        'document': value['document'],
        'participants': value['participants'] == null ? undefined : ((value['participants'] as Array<any>).map(UserDTOToJSON)),
    };
}

