CREATE DATABASE CertificateManager;

USE CertificateManager;


CREATE TABLE Suppliers (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Index INT NOT NULL,
    City VARCHAR(255) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Row_Version BYTEA
);

CREATE TABLE Users (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    First_Name VARCHAR(255) NOT NULL,
    User_Id VARCHAR(10) NOT NULL,
    Department VARCHAR(10) NOT NULL,
    Plant VARCHAR(3) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Row_Version BYTEA 
);

CREATE TABLE Certificate_Types (
    Id SERIAL PRIMARY KEY,
    Type VARCHAR(255) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Row_Version BYTEA 
);

CREATE TABLE Certificates (
    Id SERIAL PRIMARY KEY,
    Supplier_Id INT,
    Type_Id INT,
    Valid_From TIMESTAMP NOT NULL,
    Valid_To TIMESTAMP NOT NULL,
    Certificate_Document BYTEA,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Row_Version BYTEA,
    FOREIGN KEY (Supplier_Id) REFERENCES Suppliers(Id),
    FOREIGN KEY (Type_Id) REFERENCES Certificate_Types(Id)
);

CREATE TABLE Comments (
    Id SERIAL PRIMARY KEY,
    Comment_Text VARCHAR(255) NOT NULL,
    User_Id INT,
    Certificate_Id INT,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Row_Version BYTEA,
    FOREIGN KEY (User_Id) REFERENCES Users(Id),
    FOREIGN KEY (Certificate_Id) REFERENCES Certificates(Id)
);

CREATE TABLE Certificate_Users (
    Id SERIAL PRIMARY KEY,
    User_Id INT,
    Certificate_Id INT,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Row_Version BYTEA,
    FOREIGN KEY (User_Id) REFERENCES Users(Id),
    FOREIGN KEY (Certificate_Id) REFERENCES Certificates(Id)
);
